[WIP] EPMKHRDMH-348 [settings] [mobile] Mobile user settins
make-it-happen-team-org/mih-todo-app pull request #82
Opened 2017-02-15 15:52 UTC by sir13tommy

2017-02-15 23:48 UTC, ghost requested changes

2017-02-15 23:48 UTC, AinuraAliieva commented on mobile/modules/users/config/users.client.routes.es6
> +    }
we don't need this state and view for it as we don't implement this logic

2017-02-15 23:48 UTC, AinuraAliieva commented on mobile/modules/users/less/_users.settings.less
> +  font-size: ~"@{remValue}rem";
please move this logic to 'less' variables

2017-02-15 23:48 UTC, AinuraAliieva commented on mobile/modules/users/less/_users.settings.less
> +}
seems that it is a common rule for whole app (not only for settings)

2017-02-15 23:48 UTC, AinuraAliieva commented on mobile/modules/users/less/_users.settings.less
> +    background: @color-blue-whale-blue-s53;
could you use component variable (mapped from color)

2017-02-15 23:48 UTC, AinuraAliieva commented on mobile/modules/users/less/_users.settings.less
> +    color: @color-bali-hai-blue-s24;
could you use component variable (mapped from color)

2017-02-15 23:48 UTC, AinuraAliieva commented on mobile/modules/users/less/_users.settings.less
> +    height: 95px;
could we use variable for this?

2017-02-15 23:48 UTC, AinuraAliieva commented on mobile/modules/users/less/_users.settings.less
> +      color: #000000;
could you move the color to variables?

2017-02-15 23:48 UTC, AinuraAliieva commented on mobile/modules/users/less/_users.settings.less
> +.settings-header {
please use common styles for header

2017-02-16 11:08 UTC, make-it-happen-team requested changes

2017-02-16 11:08 UTC, make-it-happen-team commented on mobile/modules/users/less/_users.settings.less
> +    color: @color-white;
could you use component variable (mapped from color)

2017-02-16 11:08 UTC, make-it-happen-team commented on mobile/modules/users/less/_users.settings.less
> +  @avatar-size: 95px;
please declare variables on the top of the file

2017-02-16 11:37 UTC, merged