[WIP] EPMKHRDMH-325 Mobile task list
make-it-happen-team-org/mih-todo-app pull request #83
Opened 2017-02-15 22:03 UTC by olha-kurkaiedova

finished styling tasks list;
added controller for TasksList;
Added service for percentage chart;

2017-02-15 23:30 UTC, ghost requested changes

2017-02-15 23:30 UTC, AinuraAliieva commented on mobile/modules/events/less/_events.details.less
>        background-color: @color-white;
could you use component variable (mapped from color)

2017-02-15 23:30 UTC, AinuraAliieva commented on mobile/modules/events/less/_events.details.less
>          color: #777;
could you use component variable (mapped from color)

2017-02-15 23:30 UTC, AinuraAliieva commented on mobile/modules/tasks/controllers/tasksDetails.client.controller.es6
> +            this.task.taskPriorityText = this.priorityForHuman(res);
could we take outside this logic (on promise then) to separate function?

2017-02-15 23:30 UTC, AinuraAliieva commented on mobile/modules/tasks/controllers/tasksList.client.controller.es6
> +        this.setFiltersToLocalStorage();
could we take outside logic for each of 'case' to separate function?

2017-02-15 23:30 UTC, AinuraAliieva commented on mobile/modules/tasks/controllers/tasksList.client.controller.es6
> +          this.filteredTasks     = resolved;
could you name the params more intuitive (resolved - maybe tasks?)
why we created the copy of the tasks property? (tasks/filteredTasks)

2017-02-15 23:30 UTC, AinuraAliieva commented on mobile/modules/tasks/less/_task-details.less
> +      & .icon-4 { color: @priority-4-color; }
we have classes for this case

_.item-priority-1_ and so on

2017-02-15 23:30 UTC, AinuraAliieva commented on mobile/modules/tasks/less/_task-list.less
>      background-color: @color-white;
could you use component variable (mapped from color)

2017-02-15 23:30 UTC, AinuraAliieva commented on mobile/modules/tasks/services/tasksList.client.service.es6
> +                    return '';
do we need formatter?

2017-02-15 23:30 UTC, AinuraAliieva commented on mobile/modules/tasks/views/list-tasks.client.view.html
> +        There are no completed tasks <br/>Please <button type="button" class="sidebar-button__reset" ng-click="taskListCtrl.resetCompleteFilter()">reset</button> filter to display all tasks.
please use _data-_ prefix

2017-02-15 23:34 UTC, olha-kurkaiedova commented on mobile/modules/tasks/controllers/tasksList.client.controller.es6
> +          this.filteredTasks     = resolved;
filtered tasks were created to give an ability to filter completed/incomplete tasks; this was done previously in taskController for desktop app

2017-02-15 23:39 UTC, olha-kurkaiedova commented on mobile/modules/tasks/services/tasksList.client.service.es6
> +                    return '';
No, we don't really need it. removed. thanks

2017-02-15 23:39 UTC, olha-kurkaiedova commented on mobile/modules/tasks/views/list-tasks.client.view.html
> +        There are no completed tasks <br/>Please <button type="button" class="sidebar-button__reset" ng-click="taskListCtrl.resetCompleteFilter()">reset</button> filter to display all tasks.
fixed

2017-02-15 23:42 UTC, olha-kurkaiedova commented on mobile/modules/tasks/less/_task-details.less
> +      & .icon-4 { color: @priority-4-color; }
no, we have classes not for color itself, but for some specific rule for task list

2017-02-15 23:45 UTC, olha-kurkaiedova commented on mobile/modules/events/less/_events.details.less
>          color: #777;
yep, thanks

2017-02-15 23:52 UTC, olha-kurkaiedova commented on mobile/modules/tasks/less/_task-list.less
>      background-color: @color-white;
fixed

2017-02-15 23:52 UTC, olha-kurkaiedova commented on mobile/modules/events/less/_events.details.less
>        background-color: @color-white;
fixed

2017-02-15 23:58 UTC, AinuraAliieva commented on mobile/modules/tasks/controllers/tasksList.client.controller.es6
> +          this.filteredTasks     = resolved;
ok, thank you for the clarification

2017-02-16 00:07 UTC, AinuraAliieva commented on mobile/modules/tasks/less/_task-details.less
> +      & .icon-4 { color: @priority-4-color; }
ok, sorry for misunderstanding. we are going to update it next time (in scope of associated tickets #328, #329)

2017-02-16 09:11 UTC, merged